### ISSUE TITLE
Mano model

### ISSUE THREAD

**Issue by abcliguanxi** [Smorodov/nano_smpl#1]
hi，thks for your great work. I did not find mano.cpp and mano.h. would you provide the mano model class definition?
if i use the smpl class of your project, here is the result

https://user-images.githubusercontent.com/37575076/146323086-2f6db761-6c64-4dea-bd50-6507dd2653df.mp4

**Comment by Smorodov** [comment]
Hi, looks like model versions issue, check with this model please: https://drive.google.com/file/d/1I4XDYTqyORv-kUDeburQWKEB-NhI23e2/view?usp=sharing

**Comment by abcliguanxi** [comment]
> Hi, looks like model versions issue, check with this model please: https://drive.google.com/file/d/1I4XDYTqyORv-kUDeburQWKEB-NhI23e2/view?usp=sharing
i used your mano model.but the result is same as before.

**Comment by Smorodov** [comment]
Which system do you use?
I just rebuilt the project, it works fine. 
My system:
Windows 10
vs2019 
x64

**Comment by Smorodov** [comment]
It also may be endianness issue. 
Seems PC uses big endian, and apple uses little endian byte order.
I do not use mac's, so can't check if it will work there.

**Comment by abcliguanxi** [comment]
> It also may be endianness issue. Seems PC uses big endian, and apple uses little endian byte order. I do not use mac's, so can't check if it will work there.
my enviroment:
windows 10
vs2019
x64
cpu: Intel(R) Core(TM) i5-7500 
gpu:Intel(R) HD Graphics 630


you use the code from current branch?  could you share your code that just rebuilt for comparing the code difference.

**Comment by Smorodov** [comment]
Sure, no problem.
https://drive.google.com/file/d/1-zHLladV6CTmGTFwFNB8DI22Awis1I1r/view?usp=sharing
It is full project with binaries.

**Comment by Smorodov** [comment]
I use NVidia GPU (GTX 1070), may be shaders works in different manner.

**Comment by abcliguanxi** [comment]
> Sure, no problem. https://drive.google.com/file/d/1-zHLladV6CTmGTFwFNB8DI22Awis1I1r/view?usp=sharing It is full project with binaries.

hi,thks for your full project.  i compared your full project  and the project that i downloaded from your github.there is some difference between two project. I used your full project and rebuilt.Now,i get the correct result.finally,thks for your reply and help!

**Comment by Smorodov** [comment]
Thanks for your feedback !
I will update the repository in nearest time.

**Comment by denniskb** [comment]
I am trying to use your code to load (and animate) the Mano hand. The vertices look fine, but the indices do not form proper triangles:

<img width="402" alt="image" src="https://github.com/Smorodov/nano_smpl/assets/3048091/856c1193-2074-4425-8ad9-35113cf49ef6">

I tried to switch to the model file you provide in this issue as well as copy-paste your code form gdrive over the one cloned from this repo (just in case there was any divergence) - to no avail.
